### ISSUE TITLE
Compatibility for RSpec 4 onwards

### ISSUE THREAD

**Issue by Physium** [mike-zorn/rspec-teamcity#6]
Is this gem no longer in the works to support the latest rspec version?

**Comment by mike-zorn** [comment]
Hi, unfortunately this is not actively maintained, so nothing is in the works. If you submit a pull request to add support for the new version, I'm happy to release a new version of this gem.

**Comment by Physium** [comment]
Fair enough. Would this work if we just relax the rspec dependency for a start?

**Comment by mike-zorn** [comment]
Hmmm, What rspec version are you trying to use? The latest version of [rspec on rubygems](https://rubygems.org/gems/rspec) appears to be 3.12.0.

**Comment by Physium** [comment]
ah my sincere apologies. i entirely mixed up rspec-rails versions with rspec versions. will close this issue.
